# See https://stonecutter.kikugie.dev/wiki/config/properties#centralized-properties
mod.id = "skyblock_enhancements"
mod.name = "SkyBlock Enhancements"
mod.group = "com.github.kd_gaming1"
mod.version = "1.2.1"

deps.fabric_loader = "0.19.5"
loomx.loom_version = "1.17-SNAPSHOT"

["26.2"]
mod.mc_compat = "~26.2"
mod.mc_releases = ["26.2"]

deps.fabric_api = "0.158.0+26.2"
deps.midnightlib_version = "1.9.3+26.2-fabric"
deps.modmenu_version = "20.0.1"
deps.hm_api_version = "1.0.4+26.2"
deps.uilib_version="21.1.1"
deps.architectury_api_version="20.0.6+fabric"
deps.rpc_version="1.2.7"
